// <auto-generated />
namespace Hat_Trick.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Mach2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mach2));
        
        string IMigrationMetadata.Id
        {
            get { return "201804161013133_Mach2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
